health:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: NRNGLTJ-ST65918
      user: ABHIDATAANALYTIC
      password: 
      role: ACCOUNTADMIN
      database: HEALTH
      warehouse: TRANSFORMING_WH
      schema: RAW
      threads: 4